EMP = LOAD '/home/itelligence/Desktop/EMP.json' USING JsonLoader 
('EMPLOYEE_ID:INT,FIRST_NAME:CHARARRAY,LAST_NAME:CHARARRAY,
EMAIL:CHARARRAY,PHONE_NUMBER:CHARARRAY,HIRE_DATE:CHARARRAY,
JOB_ID:CHARARRAY,SALARY:INT,MANAGER_ID:CHARARRAY,
DEPARTMENT_ID:CHARARRAY');

